<?php

$html_header_1_02 = '<a href="#item_1_02">1.02   Introduction: Parents\' Desire to Effect Complete Agreement</a>';
$html_header_1_03 = '<a href="#item_1_03">1.03   Introduction: Parents Do Not Intend to Seek Family Court Approval</a>';
$html_header_2_00 = '<a href="#item_2_00">2.00   Guiding Principles. Responsibilities to Our Child(ren)</a>';
$html_header_2_01 = '<a href="#item_2_01">2.01   Guiding Principles. Responsibilities to Our Co-Parent</a>';
$html_header_2_02 = '<a href="#item_2_02">2.02   Guiding Principles. Statement About New Intimate Partners</a>';
$html_header_2_03 = '<a href="#item_2_03">2.03   Guiding Principles. Protection from Parental Disputes</a>';
$html_header_3_00 = '<a href="#item_3_00">3.00   Parties: Information on William Simmons</a>';
$html_header_3_01 = '<a href="#item_3_01">3.01   Parties: Information on William Rudolpho</a>';
$html_header_4_00 = '<a href="#item_4_00">4.00   Children: Information on the Child(ren)</a>';
$html_header_5_00 = '<a href="#item_5_00">5.00   Legal Custody: Definition</a>';
$html_header_5_01 = '<a href="#item_5_01">5.01   Legal Custody: Joint to Both Parents</a>';
$html_header_5_02 = '<a href="#item_5_02">5.02   Legal Custody: Sole to One Parent</a>';
$html_header_5_03 = '<a href="#item_5_03">5.03   Legal Custody: Parents Must Consult but One Parent has Tie-Breaking Authority</a>';
$html_header_5_04 = '<a href="#item_5_04">5.04   Legal Custody: Parents Must Consult but there is a Division of Authority</a>';
$html_header_5_05 = '<a href="#item_5_05">5.05   Legal Custody: Access to Information for Parent Without Legal Custody</a>';
$html_header_5_06 = '<a href="#item_5_06">5.06   Legal Custody: Emergency Contacts for the Child(ren)</a>';
$html_header_5_07 = '<a href="#item_5_07">5.07   Legal Custody: Expert Advice When Making Legal Custody Decisions</a>';
$html_header_5_08 = '<a href="#item_5_08">5.08   Legal Custody: Day-to-Day Decisions</a>';
$html_header_5_09 = '<a href="#item_5_09">5.09   Legal Custody: Emergency Decisions</a>';
$html_header_5_10 = '<a href="#item_5_10">5.10   Legal Custody: Health Emergency or Death of the Other Parent</a>';
$html_header_5_11 = '<a href="#item_5_11">5.11   Legal Custody: Parallel Parenting</a>';
$html_header_6_00 = '<a href="#item_6_00">6.00   Physical Custody and Timesharing: Global Priority</a>';
$html_header_6_01 = '<a href="#item_6_01">6.01   Physical Custody and Timesharing: Timesharing During the School Year</a>';
$html_header_6_01A = '<a href="#item_6_01A">6.01A   Equal Timesharing Schedules</a>';
$html_header_6_01B = '<a href="#item_6_01B">6.01B   Other Timesharing Schedules</a>';
$html_header_6_02 = '<a href="#item_6_02">6.02   Physical Custody and Timesharing: Timesharing During the School Breaks</a>';
$html_header_6_02A = '<a href="#item_6_02A">6.02A   Fall Break</a>';
$html_header_6_02A_i = '<a href="#item_6_02A_i">6.02A(i)   Split Break</a>';
$html_header_6_02A_ii = '<a href="#item_6_02A_ii">6.02A(ii)   Alternate Break</a>';
$html_header_6_02A_iii = '<a href="#item_6_02A_iii">6.02A(iii)   Continue Schedule During the School Year</a>';
$html_header_6_02B = '<a href="#item_6_02B">6.02B   Thanksgiving Break</a>';
$html_header_6_02B_i = '<a href="#item_6_02B_i">6.02B(i)   Split Break</a>';
$html_header_6_02B_ii = '<a href="#item_6_02B_ii">6.02B(ii)   Alternate Break</a>';
$html_header_6_02B_iii = '<a href="#item_6_02B_iii">6.02B(iii)   Time on Thanksgiving Day</a>';
$html_header_6_02B_iv = '<a href="#item_6_02B_iv">6.02B(iv)   Continue Schedule During the School Year</a>';
$html_header_6_02C = '<a href="#item_6_02C">6.02C   Winter Break</a>';
$html_header_6_02C_i = '<a href="#item_6_02C_i">6.02C(i)   Split Break</a>';
$html_header_6_02C_ii = '<a href="#item_6_02C_ii">6.02C(ii)   Alternate Break</a>';
$html_header_6_02C_iii = '<a href="#item_6_02C_iii">6.02C(iii)   Split Break with Holiday Time</a>';
$html_header_6_02C_iv = '<a href="#item_6_02C_iv">6.02C(iv)   Continue Schedule During the School Year</a>';
$html_header_6_02D = '<a href="#item_6_02D">6.02D   Spring Break</a>';
$html_header_6_02D_i = '<a href="#item_6_02D_i">6.02D(i)   Split Break</a>';
$html_header_6_02D_ii = '<a href="#item_6_02D_ii">6.02D(ii)   Alternate Break</a>';
$html_header_6_02D_iii = '<a href="#item_6_02D_iii">6.02D(iii)   Continue Scheduling During the School Year</a>';
$html_header_6_02E = '<a href="#item_6_02E">6.02E   Summer Break</a>';
$html_header_6_02E_i = '<a href="#item_6_02E_i">6.02E(i)   Split Break</a>';
$html_header_6_02E_ii = '<a href="#item_6_02E_ii">6.02E(ii)   Continue Schedule During the School Year</a>';
$html_header_6_02E_iii = '<a href="#item_6_02E_iii">6.02E(iii)   Continue Schedule During the School Year with Option for Uninterrupted Time</a>';
$html_header_6_03 = '<a href="#item_6_03">6.03   Physical Custody and Timesharing: Holidays and Special Days</a>';
$html_header_6_03A = '<a href="#item_6_03A">6.03A   Alternate Yearly</a>';
$html_header_6_03B = '<a href="#item_6_03B">6.03B   Split Every Year</a>';
$html_header_6_03C = '<a href="#item_6_03C">6.03C   Monday/Friday Holidays Attached to a Weekend</a>';
$html_header_6_03D = '<a href="#item_6_03D">6.03D   Every Year with William Simmons or William Rudolpho</a>';
$html_header_6_04 = '<a href="#item_6_04">6.04   Physical Custody and Timesharing: Travel with the Child(ren)</a>';
$html_header_6_05 = '<a href="#item_6_05">6.05   Physical Custody and Timesharing: Rescheduling and Make-Up Time</a>';
$html_header_6_06 = '<a href="#item_6_06">6.06   Physical Custody and Timesharing: Right of First Refusal</a>';
$html_header_6_07 = '<a href="#item_6_07">6.07   Physical Custody and Timesharing: Pick-Up for Non-School Exchanges</a>';
$html_header_6_08 = '<a href="#item_6_08">6.08   Physical Custody and Timesharing: Drop Off for Non-School Exchanges</a>';
$html_header_6_09 = '<a href="#item_6_09">6.09   Physical Custody and Timesharing: Exchanges at a Neutral Location</a>';
$html_header_6_10 = '<a href="#item_6_10">6.10   Physical Custody and Timesharing: Parental Authority to Delegate Pick-Up and Drop Off the Child(ren)</a>';
$html_header_6_11 = '<a href="#item_6_11">6.11   Physical Custody and Timesharing: Persons Authorized to Pick Up and Drop Off the Child(ren)</a>';
$html_header_6_12 = '<a href="#item_6_12">6.12   Physical Custody and Timesharing: Child(ren)\'s Personal Belongings</a>';
$html_header_6_13 = '<a href="#item_6_13">6.13   Physical Custody and Timesharing: Relocation</a>';
$html_header_6_14 = '<a href="#item_6_14">6.14   Physical Custody and Timesharing: Modification of Schedule by Agreement of Both Parents</a>';
$html_header_7_00 = '<a href="#item_7_00">7.00   Communication</a>';
$html_header_7_01 = '<a href="#item_7_01">7.01   Communication Between Co-Parents: E-mail Only</a>';
$html_header_7_02 = '<a href="#item_7_02">7.02   Communication Between Co-Parents: E-mail and Text Only</a>';
$html_header_7_03 = '<a href="#item_7_03">7.03   Communication Between Co-Parents: Our Family Wizard or Other Mutually Agreed Upon Parenting Communication Application</a>';
$html_header_7_04 = '<a href="#item_7_04">7.04   Communication Between Co-Parents: Monthly Conference</a>';
$html_header_7_05 = '<a href="#item_7_05">7.05   Communication Between Co-Parents: Semi Annual Conference</a>';
$html_header_7_06 = '<a href="#item_7_06">7.06   Communication Between Co-Parents: Annual Conference</a>';
$html_header_7_07 = '<a href="#item_7_07">7.07   Communication Between Child(ren) and Non-Custodial Parent: Unlimited</a>';
$html_header_7_08 = '<a href="#item_7_08">7.08   Communication Between Child(ren) and Non-Custodial Parent: Specific</a>';
$html_header_7_09 = '<a href="#item_7_09">7.09   Communication: Exchange of Contact Information</a>';
$html_header_7_10 = '<a href="#item_7_10">7.10   Communication: Scheduling Extracurricular Activities for the Child(ren)</a>';
$html_header_7_11 = '<a href="#item_7_11">7.11   Communication: Selecting Extracurricular Activities for the Child(ren)</a>';
$html_header_8_00 = '<a href="#item_8_00">8.00   Support of the Child(ren): Child Support Guidelines Amount Under the Law</a>';
$html_header_8_01 = '<a href="#item_8_01">8.01   Support of the Child(ren): Child Support Guidelines Amount When Parents Reside in the Same State</a>';
$html_header_8_02 = '<a href="#item_8_02">8.02   Support of the Child(ren): Child Support Guidelines Amount When Parents Reside in Different States</a>';
$html_header_8_03 = '<a href="#item_8_03">8.03   Support of the Child(ren): Mutually Agreed Upon Amount Alternative</a>';
$html_header_8_04 = '<a href="#item_8_04">8.04   Support of the Child(ren): No Agreement of the Parties Re Monthly Child Support Amount and/or Jurisdiction</a>';
$html_header_8_05 = '<a href="#item_8_05">8.05   Support of the Child(ren): Child Support Account Alternative</a>';
$html_header_8_06 = '<a href="#item_8_06">8.06   Support of the Child(ren): Direct Payment of the Child Support</a>';
$html_header_8_07 = '<a href="#item_8_07">8.07   Support of the Child(ren): Payment of Child Support Through the State Child Support Enforcement Agency</a>';
$html_header_8_08 = '<a href="#item_8_08">8.08   Support of the Child(ren): Health Insurance Premiums</a>';
$html_header_8_09 = '<a href="#item_8_09">8.09   Support of the Child(ren): Uninsured Co-Pays for Health-Related Expenses</a>';
$html_header_8_09A = '<a href="#item_8_09A">8.09A   Sole Responsibility</a>';
$html_header_8_09B = '<a href="#item_8_09B">8.09B   Split Responsibility</a>';
$html_header_8_09C = '<a href="#item_8_09C">8.09C   Responsibility for Threshold Amount</a>';
$html_header_8_09D = '<a href="#item_8_09D">8.09D   Definition of Uninsured Health-Related Expenses: Recommended by Providers</a>';
$html_header_8_09E = '<a href="#item_8_09E">8.09E   Definition of Uninsured Health-Related Expenses: Mutual Agreement of the Parents</a>';
$html_header_8_10 = '<a href="#item_8_10">8.10   Support of the Child(ren): Extracurricular Expenses</a>';
$html_header_8_10A = '<a href="#item_8_10A">8.10A   Sole Responsibility</a>';
$html_header_8_10B = '<a href="#item_8_10B">8.10B   Split Responsibility</a>';
$html_header_8_10C = '<a href="#item_8_10C">8.10C   Selecting Extracurricular Activities for the Child(ren) Pursuant to 7.10 Hereinabove</a>';
$html_header_8_10D = '<a href="#item_8_10D">8.10D   Extracurricular Activities Must Be Mutually Agreed Upon</a>';
$html_header_8_11 = '<a href="#item_8_11">8.11   Support of the Child(ren): Private School Expenses</a>';
$html_header_8_11A = '<a href="#item_8_11A">8.11A   Sole Responsibility</a>';
$html_header_8_11B = '<a href="#item_8_11B">8.11B   Split Responsibility</a>';
$html_header_8_11C = '<a href="#item_8_11C">8.11C   Definition of Private School Expenses</a>';
$html_header_8_11D = '<a href="#item_8_11D">8.11D   Mutual Agreement of Parents</a>';
$html_header_8_11E = '<a href="#item_8_11E">8.11E   Reserve</a>';
$html_header_8_12 = '<a href="#item_8_12">8.12   Support of the Child(ren): Post-High School Expenses</a>';
$html_header_8_12A = '<a href="#item_8_12A">8.12A   Sole Responsibility</a>';
$html_header_8_12B = '<a href="#item_8_12B">8.12B   Split Responsibility</a>';
$html_header_8_12C = '<a href="#item_8_12C">8.12C   Sole Responsibility After Funds from Any 529 Accounts held on Behalf of a Child or Children, Coverdell Accounts of Other Funds</a>';
$html_header_8_12D = '<a href="#item_8_12D">8.12D   Split Responsibility After Funds from Any 529 Accounts held on Behalf of a Child or Children, Coverdell Accounts of Other Funds Ear-Marked to Pay for a Child\'s Post-High School Education Expenses</a>';
$html_header_8_12E = '<a href="#item_8_12E">8.12E   Cap on Payment by Each Parent per Academic School Year</a>';
$html_header_8_12F = '<a href="#item_8_12F">8.12F   Definition of Post-High School Education Expenses</a>';
$html_header_8_12G = '<a href="#item_8_12G">8.12G   Mutual Agreement of Parents</a>';
$html_header_8_12H = '<a href="#item_8_12H">8.12H   Reserve</a>';
$html_header_8_13 = '<a href="#item_8_13">8.13   Support of the Child(ren): Claiming the Child(ren) as a Dependent for Tax Purposes</a>';
$html_header_8_13A = '<a href="#item_8_13A">8.13A   Sole Authority to Claim the Child(ren)</a>';
$html_header_8_13B = '<a href="#item_8_13B">8.13B   Split Authority to Claim the Child(ren)</a>';
$html_header_8_13C = '<a href="#item_8_13C">8.13C   Split Authority to Claim the Child(ren) then Alternate</a>';
$html_header_8_13D = '<a href="#item_8_13D">8.13D   Alternate Authority to Claim the Child(ren)</a>';
$html_header_8_14 = '<a href="#item_8_14">8.14   Support of the Child(ren): Protocols for Reimbursement of Child-Related Expenses</a>';
$html_header_8_14A = '<a href="#item_8_14A">8.14A   Timeframe for Reimbursement of Child-Related Expenses and Reimbursement</a>';
$html_header_8_14B = '<a href="#item_8_14B">8.14B   Monthly Calculation of Child-Related Expenses and Reimbursement</a>';
$html_header_8_14C = '<a href="#item_8_14C">8.14C   Quarterly Calculation of Child-Related Expenses and Reimbursement</a>';
$html_header_8_14D = '<a href="#item_8_14D">8.14D   Annual Calculation of Child-Related Expenses and Reimbursement</a>';
$html_header_8_14E = '<a href="#item_8_14E">8.14E   Documentation Required for Reimbursement of Child-Related Expenses</a>';
$html_header_8_14F = '<a href="#item_8_14F">8.14F   Reimbursement Method</a>';
$html_header_9_00 = '<a href="#item_9_00">9.00   Other Issues: Co-Parent Counseling</a>';
$html_header_9_01 = '<a href="#item_9_01">9.01   Other Issues: Child-Focused Therapist</a>';
$html_header_9_02 = '<a href="#item_9_02">9.02   Other Issues: Social Media Between Parents</a>';
$html_header_9_03 = '<a href="#item_9_03">9.03   Other Issues: Social Media For Child(ren)</a>';
$html_header_9_04 = '<a href="#item_9_04">9.04   Other Issues: Joint Parent-Teacher Meetings</a>';
$html_header_9_05 = '<a href="#item_9_05">9.05   Other Issues: Separate Parent-Teacher Meetings</a>';
$html_header_9_06 = '<a href="#item_9_06">9.06   Other Issues: One Parent to Attend Parent-Teacher Meetings</a>';
$html_header_9_07 = '<a href="#item_9_07">9.07   Other Issues: Report Cards for the Child(ren)</a>';
$html_header_9_08 = '<a href="#item_9_08">9.08   Other Issues: Joint Attendance at School and Extracurricular Events</a>';
$html_header_9_09 = '<a href="#item_9_09">9.09   Other Issues: Custodial Parent to Attend School and Extracurricular Events</a>';
$html_header_9_10 = '<a href="#item_9_10">9.10   Other Issues: Alternate Attendance at School and Extracurricular Events</a>';
$html_header_9_11 = '<a href="#item_9_11">9.11   Other Issues: Documents</a>';
$html_header_9_12 = '<a href="#item_9_12">9.12   Other Issues: Joint Authority to Consent for Passport</a>';
$html_header_9_13 = '<a href="#item_9_13">9.13   Other Issues: Sole Authority to Consent for Passport</a>';
$html_header_9_14 = '<a href="#item_9_14">9.14   Other Issues: New Intimate Partner Protocols (Less Detailed)</a>';
$html_header_9_15 = '<a href="#item_9_15">9.15   Other Issues: New Intimate Partner Protocols (More Detailed)</a>';
$html_header_9_16 = '<a href="#item_9_16">9.16   Other Issues: Alternative Dispute Resolution</a>';
$html_header_10_00 = '<a href="#item_10_00">10.00   Legal: Continuing Jurisdiction</a>';
$html_header_10_01 = '<a href="#item_10_01">10.01   Legal: Enforcement</a>';
$html_header_10_02 = '<a href="#item_10_02">10.02   Legal: Voluntary Execution</a>';

// Output example for accessing an item
echo $html_header_1_02; // This will output the anchor tag for "1.02   Introduction: Parents' Desire to Effect Complete Agreement"

?>
